### ISSUE TITLE
Service Status Component

### ISSUE THREAD

**Issue by christiankiller** [blockchain-signaling-system/bloss-dashboard#1]
## Intro
This component directly interacts with the `service-status-feature` offered by `bloss-node` and retrieves its information from there. 

### TODO
**The `Service Status` Component should**
- [x] ... **display the statuses of the services running** on the respective controller (i.e.`geth.service`, `bloss.service`, `ipfs.service` and the connection / status to the local `influxdb`)
- [x] ... keep it simple and **only display two different statuses**: **INACTIVE (DEAD)** or **ACTIVE (RUNNING)**
- [x] ... enable **control** **(start/stop/restart)** over the statuses of the services running on the respective controller (i.e.`geth.service`, `bloss.service`, `ipfs.service` and `influxdb.service`)

### Nice-to-have
- [ ] ... display a "loading" status, however this can become very tricky and hacky due to the relayed nature of the information retrieval via `bloss-node`
- [ ] ... **manage state of the statuses with Vuex**, which means implementation of meaningful mutations / actions and state variables.

**Comment by christiankiller** [comment]
#### Restructured issue, Nice-to-haves for later Milestones. 
Basic functionality is implemented and enough for now.

### Additional Nice-to-have would be
- [ ] ... the possibility to retrieve content of `journalctl` logs via the click of a button, which shouldn't be a huge hassle but another endpoint and another communication overhead.
