### ISSUE TITLE
MREQ Component

### ISSUE THREAD

**Issue by christiankiller** [blockchain-signaling-system/bloss-dashboard#2]
## Intro
- This component directly interacts with the `mitigation-request-feature` offered by `bloss-node`.
- This component basically enables the operator to see incoming mitigation requests and gives him the opportunity to take informed decisions on mitigation requests.
- These decisions are then sent and persisted on the `bloss-node` relay via websockets and from there they're sent to the bloss-core instance on the controller. 

### TODO
**The `Mitigation Requests` Component should**
- [x] ... **display three kanban-style board queues**, the first queue on the left shows new requests (kanban-analogy: ToDo), the second queue shows processing requests and the third is a simple text-log of past mitigation requests.

### TODO (focus on one element)
**The `Mitigation Requests` Component should**
- [x] ... **contain properly formatted elements**
- [x] ... **offer easy accept / decline & detail functionality**

_No Nice-to-haves since this component really is the core of the whole dashboard._
