### ISSUE TITLE
Test MREQ Component for timing and usability constraints

### ISSUE THREAD

**Issue by christiankiller** [blockchain-signaling-system/bloss-dashboard#7]
# Further test MREQ component functionality for stability and timing constraints. 
**Functionality / Stability perspective**
**How long do we have to react to a request so 
- [ ] A) that it makes sense to even reply and 
- [ ] B) Should there be a timer that counts and 'auto-replies' after a certain time?

Both things basically assume that there is some **timing** constraint that has to be found or defined. 

### TODO
- [ ] _Add functionalities to implement, after evaluation_

**Comment by christiankiller** [comment]
On hold. 
Maybe reopen in later MS if any issues arise. 
As of now this doesn't pose and problems since reaction time is rather swift.
