### ISSUE TITLE
REQM Component

### ISSUE THREAD

**Issue by christiankiller** [blockchain-signaling-system/bloss-dashboard#9]
## Intro
REQM stands for **REQ**uest **M**itigation.
The REQM component handles the outgoing mitigation requests that can be manually triggered by ASes. The exact TODO's and feature set of this component needs to be well-defined and relies heavily on the implementation complexity regarding necessary changes of `bloss-core`. 

## TODO's
**The REQM component ...**
- [x] **... enables an operator to trigger an REQ for Mitigation.**

**bloss-core spams with alarms every second, hence:**
- [x] The frontend should update the displayed alarm every time, as long as the attackers, the target and the origin subnet don't diverge. 
~Make sure the POST to /report of core really worked - **catch** exceptions and check the response of core if it worked, **else** don't change the state of the alarm and send NEW_ALARM BACK?~

**Comment by christiankiller** [comment]
- [ ] As of now there are multiple boxes for the same hash (displaying different states returned by `bloss-node`) -> Handle state managemnt as soon as new alarms arrive via `alarmChannel`. 
- [ ] Add loading states when `*_REQUESTED` or `*_IN_PROGRESS`
